// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Candidate is a device waiting to be confirmed by its check code.
 */
export interface Candidate {
    "id": string;
    "name": string;
    "code": string;
}

/**
 * Offer is one incoming offer on a receive session.
 */
export interface Offer {
    "from": number;
    "id": string;
    "name": string;
    "kind": string;
    "items": number;
    "bytes": number;
    "done": number;
    "status": string;
    "error"?: string;
    "folder"?: string;
    "text"?: string;
}

/**
 * Pairing is an open pairing session and who has introduced themselves.
 */
export interface Pairing {
    "phrase": string;
    "link": string;
    "candidates": Candidate[] | null;
}

/**
 * Peer is a paired device.
 */
export interface Peer {
    "id": string;
    "name": string;
    "paired": string;
}

/**
 * Session is one open share or receive.
 */
export interface Session {
    "phrase": string;
    "link": string;
    "title": string;
    "items": number;
    "bytes": number;
    "peers": number;
    "delivered": number;
    "status": string;
    "started": string;

    /**
     * the paired device, if any
     */
    "peer"?: string;
    "offers"?: Offer[] | null;
}

/**
 * State is everything the window and tray render, as plain data: it is
 * serialized straight to the frontend.
 */
export interface State {
    "shares": Session[] | null;
    "receives": Session[] | null;
    "peers": Peer[] | null;
    "pairings": Pairing[] | null;
}
