// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Candidate is a device waiting to be confirmed by its check code.
 */
export class Candidate {
    "id": string;
    "name": string;
    "code": string;

    /** Creates a new Candidate instance. */
    constructor($$source: Partial<Candidate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Candidate instance from a string or object.
     */
    static createFrom($$source: any = {}): Candidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Candidate($$parsedSource as Partial<Candidate>);
    }
}

/**
 * Offer is one incoming offer on a receive session.
 */
export class Offer {
    "from": number;
    "id": string;
    "name": string;
    "kind": string;
    "items": number;
    "bytes": number;
    "done": number;
    "status": string;
    "error"?: string;
    "folder"?: string;
    "text"?: string;

    /** Creates a new Offer instance. */
    constructor($$source: Partial<Offer> = {}) {
        if (!("from" in $$source)) {
            this["from"] = 0;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Offer instance from a string or object.
     */
    static createFrom($$source: any = {}): Offer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Offer($$parsedSource as Partial<Offer>);
    }
}

/**
 * Pairing is an open pairing session and who has introduced themselves.
 */
export class Pairing {
    "phrase": string;
    "link": string;
    "candidates": Candidate[];

    /** Creates a new Pairing instance. */
    constructor($$source: Partial<Pairing> = {}) {
        if (!("phrase" in $$source)) {
            this["phrase"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pairing instance from a string or object.
     */
    static createFrom($$source: any = {}): Pairing {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField2_0($$parsedSource["candidates"]);
        }
        return new Pairing($$parsedSource as Partial<Pairing>);
    }
}

/**
 * Peer is a paired device.
 */
export class Peer {
    "id": string;
    "name": string;
    "paired": string;

    /** Creates a new Peer instance. */
    constructor($$source: Partial<Peer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("paired" in $$source)) {
            this["paired"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Peer instance from a string or object.
     */
    static createFrom($$source: any = {}): Peer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Peer($$parsedSource as Partial<Peer>);
    }
}

/**
 * Session is one open share or receive.
 */
export class Session {
    "phrase": string;
    "link": string;
    "title": string;
    "items": number;
    "bytes": number;
    "peers": number;
    "delivered": number;
    "status": string;
    "started": string;

    /**
     * the paired device, if any
     */
    "peer"?: string;
    "offers"?: Offer[];

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("phrase" in $$source)) {
            this["phrase"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("peers" in $$source)) {
            this["peers"] = 0;
        }
        if (!("delivered" in $$source)) {
            this["delivered"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField10_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("offers" in $$parsedSource) {
            $$parsedSource["offers"] = $$createField10_0($$parsedSource["offers"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

/**
 * State is everything the window and tray render, as plain data: it is
 * serialized straight to the frontend.
 */
export class State {
    "shares": Session[];
    "receives": Session[];
    "peers": Peer[];
    "pairings": Pairing[];

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("shares" in $$source)) {
            this["shares"] = [];
        }
        if (!("receives" in $$source)) {
            this["receives"] = [];
        }
        if (!("peers" in $$source)) {
            this["peers"] = [];
        }
        if (!("pairings" in $$source)) {
            this["pairings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shares" in $$parsedSource) {
            $$parsedSource["shares"] = $$createField0_0($$parsedSource["shares"]);
        }
        if ("receives" in $$parsedSource) {
            $$parsedSource["receives"] = $$createField1_0($$parsedSource["receives"]);
        }
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField2_0($$parsedSource["peers"]);
        }
        if ("pairings" in $$parsedSource) {
            $$parsedSource["pairings"] = $$createField3_0($$parsedSource["pairings"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

// Private type creation functions
const $$createType0 = Candidate.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Offer.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Session.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Peer.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Pairing.createFrom;
const $$createType9 = $Create.Array($$createType8);
