// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as desk$0 from "../../../../richardwooding/satchel/internal/desk/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "busy": string;
            "state": desk$0.State;
            "view": string;
        }
    }
}
