// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings persist in the user config dir as settings.json.
 */
export interface Settings {
    "relay": string;
    "downloads": string;

    /**
     * DeviceName is what paired devices see this one as.
     */
    "deviceName": string;

    /**
     * Autostart records the Background portal's last answer (Flatpak only:
     * the portal cannot be asked what it currently allows).
     */
    "autostart"?: boolean;
}
