// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings persist in the user config dir as settings.json.
 */
export class Settings {
    "relay": string;
    "downloads": string;

    /**
     * DeviceName is what paired devices see this one as.
     */
    "deviceName": string;

    /**
     * Autostart records the Background portal's last answer (Flatpak only:
     * the portal cannot be asked what it currently allows).
     */
    "autostart"?: boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("relay" in $$source)) {
            this["relay"] = "";
        }
        if (!("downloads" in $$source)) {
            this["downloads"] = "";
        }
        if (!("deviceName" in $$source)) {
            this["deviceName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}
