// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is what the window calls. Every method returns quickly or runs
 * the slow part in the background; results arrive as "state" events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desk$0 from "../internal/desk/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Accept takes an offer from a paired device.
 */
export function Accept(phrase: string, $from: number, offerID: string): $CancellablePromise<void> {
    return $Call.ByID(1722305529, phrase, $from, offerID);
}

/**
 * Autostart reports whether satchel starts at login. In a Flatpak the
 * portal cannot be asked, so the last answer it gave is remembered.
 */
export function Autostart(): $CancellablePromise<boolean> {
    return $Call.ByID(1201103974);
}

/**
 * Call starts a confab call in the browser and copies its join link.
 */
export function Call(): $CancellablePromise<void> {
    return $Call.ByID(2349242617);
}

/**
 * CallPeer starts a call and invites a paired device to it.
 */
export function CallPeer(peerID: string): $CancellablePromise<void> {
    return $Call.ByID(2627762429, peerID);
}

/**
 * Copy puts text on the clipboard, through wl-copy where there is one: GTK's
 * clipboard needs a focused window on Wayland, and a tray app has none.
 */
export function Copy(text: string): $CancellablePromise<void> {
    return $Call.ByID(3668842004, text);
}

/**
 * Decline refuses one.
 */
export function Decline(phrase: string, $from: number, offerID: string): $CancellablePromise<void> {
    return $Call.ByID(3775776457, phrase, $from, offerID);
}

/**
 * Open starts a phrase for someone else to send to.
 */
export function Open(): $CancellablePromise<string> {
    return $Call.ByID(1181669497);
}

/**
 * PairCancel closes a pairing session.
 */
export function PairCancel(phrase: string): $CancellablePromise<void> {
    return $Call.ByID(3606944511, phrase);
}

/**
 * PairConfirm saves a device once the codes match.
 */
export function PairConfirm(phrase: string, peerID: string): $CancellablePromise<void> {
    return $Call.ByID(2160050963, phrase, peerID);
}

/**
 * PairJoin joins another device's pairing session.
 */
export function PairJoin(phrase: string): $CancellablePromise<void> {
    return $Call.ByID(2464886437, phrase);
}

/**
 * PairStart opens a pairing session and returns its phrase.
 */
export function PairStart(): $CancellablePromise<string> {
    return $Call.ByID(2162236563);
}

/**
 * PickDownloads chooses where received files go. It applies on restart,
 * since receives already open keep writing where they started.
 */
export function PickDownloads(): $CancellablePromise<string> {
    return $Call.ByID(3273932657);
}

/**
 * PickFiles opens the file dialog and shares what was chosen.
 */
export function PickFiles(folders: boolean): $CancellablePromise<void> {
    return $Call.ByID(1134267223, folders);
}

/**
 * PickFilesTo sends chosen files or a folder to a paired device.
 */
export function PickFilesTo(peerID: string, folders: boolean): $CancellablePromise<void> {
    return $Call.ByID(2148638690, peerID, folders);
}

/**
 * QR renders a link as a PNG data URL.
 */
export function QR(link: string): $CancellablePromise<string> {
    return $Call.ByID(2639767706, link);
}

/**
 * Receive joins a phrase.
 */
export function Receive(phrase: string): $CancellablePromise<void> {
    return $Call.ByID(80256210, phrase);
}

/**
 * SetAutostart turns start-at-login on or off. Inside a Flatpak, Wails'
 * autostart would write an XDG autostart file into the sandbox's private
 * config directory, which the desktop never reads — so it asks the
 * Background portal instead, the only way a sandboxed app may.
 */
export function SetAutostart(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(241102900, on);
}

/**
 * SetDeviceName changes what paired devices see this one as. It applies to
 * pairings made after the next restart.
 */
export function SetDeviceName(name: string): $CancellablePromise<void> {
    return $Call.ByID(1266455922, name);
}

/**
 * Settings returns the current settings.
 */
export function Settings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3375187032);
}

/**
 * ShareClipboard offers the clipboard and copies the link to it.
 */
export function ShareClipboard(): $CancellablePromise<void> {
    return $Call.ByID(2580870886);
}

/**
 * ShareClipboardTo sends the clipboard to a paired device.
 */
export function ShareClipboardTo(peerID: string): $CancellablePromise<void> {
    return $Call.ByID(307116571, peerID);
}

/**
 * ShareText offers text typed into the window.
 */
export function ShareText(text: string): $CancellablePromise<void> {
    return $Call.ByID(3528582607, text);
}

/**
 * ShowFolder opens the downloads folder in the file manager.
 */
export function ShowFolder(): $CancellablePromise<void> {
    return $Call.ByID(3353581624);
}

/**
 * State is the current snapshot, for the window's first render.
 */
export function State(): $CancellablePromise<desk$0.State> {
    return $Call.ByID(1463670278);
}

/**
 * Stop closes a share or receive.
 */
export function Stop(phrase: string): $CancellablePromise<void> {
    return $Call.ByID(3775538709, phrase);
}

/**
 * Unpair forgets a device.
 */
export function Unpair(peerID: string): $CancellablePromise<void> {
    return $Call.ByID(3973413130, peerID);
}

/**
 * Version is the app version.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3684017895);
}
